name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release.'
        required: true
        type: string

permissions: {}

jobs:
  release:
    runs-on: [ ubuntu-latest ]

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    permissions:
      contents: write

    steps:

      - name: Create release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          VERSION: ${{ inputs.version }}
        with:
          script: |
            const { repo, owner } = context.repo;

            let version = process.env.VERSION;
            if (version.startsWith('v')) {
              version = version.substring(1);
            }

            const tag_name = `v${version}`;
            const target_commitish = process.env.DEFAULT_BRANCH;
            const name = tag_name;

            const { data: release } = await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name,
              target_commitish,
              name,
              draft: true,
              generate_release_notes: true,
            });

            core.notice(`Created release ${release.name}: ${release.html_url}`);
